- hosts: edge
  become: true

  vars:
    base_name: iot-data-utility
    executables:
      - datagencli
      - datagenmr
    binary_prefix: iot-data-utility

  tasks:
    - name: Check Directories
      file:
        path: /usr/local/{{ base_name }}/bin
        state: directory

    - name: Check Directories
      file:
        path: /usr/local/{{ base_name }}/lib
        state: directory

    - name: Copy bin
      copy:
        src: "{{ item }}"
        dest: /usr/local/{{ base_name }}/bin
        mode: 0755
      with_items: "{{ executables }}"

    - name: Copy lib
      copy:
        src: ../target/{{ binary_prefix }}-shaded.jar
        dest: /usr/local/{{ base_name }}/lib
        mode: 0755

    - name: Link executable
      file:
        src: /usr/local/{{ base_name }}/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        mode: 0755
        state: link
      with_items: "{{ executables }}"
